---

- name: 'config'
  template:
    src:  '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner | d (omit) }}'
  loop:
    - { src: 'nginx.service.j2', dest: '/usr/lib/systemd/system/nginx.service'                           }
    - { src: 'nginx.conf.j2',    dest: '/etc/nginx/nginx.conf',                owner: '{{ nginx_user }}' }

- name: 'html'
  copy:
    src:  'index.html'
    dest: '/usr/share/doc/HTML/index.html'

- name: 'systemd'
  systemd:
    name:  'nginx'
    state: 'started'