---

- name: Check distribution
  fail:
    msg: requirement Ubuntu Server 22.04 distribution
  when:
    - ansible_distribution | lower != 'ubuntu'
    - ansible_distribution_major_version | int != 22.04
