---

- name: Initialize Kubernetes cluster
  ansible.builtin.command: '{{ k8s_init_command }}'
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Install CNI
  ansible.builtin.command: kubectl apply -f {{ k8s_cni_manifest }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Save kubeadm join command
  ansible.builtin.copy:
    content: "{{ kubeadm_init.stdout | regex_findall('kubeadm join [^\n]+') | first }}"
    dest: /tmp/kubeadm_join_command
    mode: '0600'
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Fetch kubeadm join command from control plane
  ansible.builtin.slurp:
    src: /tmp/kubeadm_join_command
  register: kubeadm_join
  when: inventory_hostname != groups['k8s_masters'][0]
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Join worker nodes to cluster
  ansible.builtin.command: "{{ kubeadm_join.content | b64decode }}"
  when: inventory_hostname != groups['k8s_masters'][0]
